mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
markerhub:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
spring:
  profiles:
    active: dev
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: